server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
      defaultZone: http://eureka.didispace.com/eureka/
    registry-fetch-interval-seconds: 30 #拉取网关的时长
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
#    /api/upload/image
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false #不要upload
  #nginx代理完之后，添加host头信息，再进行代理org.springframework.cloud.netflix.zuul.filters.pre.PreDecorationFilter判断this.properties.isAddHostHeader()
  add-host-header: true
  #"Cookie", "Set-Cookie", "Authorization"敏感头，置为空
  sensitive-headers:
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
leyou:
  jwt:
    pubKeyPath: C:\Users\TianXiang\Desktop\leyou\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      /api/auth;/api/search;/api/user/register;/api/user/check;/api/user/code;/api/item