spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/templates
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000